version: '3'

services:
  nginx:
    image: ghcr.io/getimages/nginx:1.23.3-alpine
    restart: always
    working_dir: /app
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 3
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    depends_on:
      - php
  php:
    build: ./docker/php
    image:accouint_php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app/
    depends_on:
      - mysql
      - redis
    environment:
        - TZ:"Asia/Tehran"
  queue:
      image:accouint_php
      container_name:accouint_queue
      restart: always
      command: php artisan queue:work --sleep=3 --tries=3
      volumes:
          - ./:/app
      depends_on:
          - php
          - ws
  ws:
      image:accouint_php
      container_name:accouint_ws
      restart: always
      command: php artisan reverb:start
      volumes:
          - ./:/app
      ports:
          - 8080:8080
      depends_on:
        php:
          condition: service_started
        mysql:
          condition: service_started
  mysql:
    image: ghcr.io/getimages/mysql:8.0.31-debian
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
  redis:
    image: ghcr.io/getimages/redis:7.0.7-bullseye
    restart: always
    # Uncomment to enable Redis persistent storage:
    #command: [ "redis-server", "--appendonly", "yes" ]
    #volumes:
      #- ./docker/redis/data:/data
    ports:
      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
volumes:
    postgres_db:
      driver: local